# Generated by Django 3.0.5 on 2020-04-28 19:52

from django.db import migrations

from transaction_management.migrations.utils import seed_categories


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories)
    ]
